cmake_minimum_required(VERSION 3.16)
project(warpsim CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(warpsim_core src/sim.cpp src/cache.cpp)
target_include_directories(warpsim_core PUBLIC include)

add_executable(test_v0 tests/test_v0.cpp)
target_link_libraries(test_v0 PRIVATE warpsim_core)
add_executable(test_v1 tests/test_v1.cpp)
target_link_libraries(test_v1 PRIVATE warpsim_core)
add_executable(test_v2 tests/test_v2.cpp)
target_link_libraries(test_v2 PRIVATE warpsim_core)
add_executable(test_cache tests/test_cache.cpp)
target_link_libraries(test_cache PRIVATE warpsim_core)

enable_testing()
add_test(NAME v0 COMMAND test_v0)
add_test(NAME v1 COMMAND test_v1)
add_test(NAME v2 COMMAND test_v2)
add_test(NAME cache COMMAND test_cache)

add_executable(test_v2b tests/test_v2b.cpp)
target_link_libraries(test_v2b PRIVATE warpsim_core)
add_test(NAME v2b COMMAND test_v2b)

add_executable(test_v3 tests/test_v3.cpp)
target_link_libraries(test_v3 PRIVATE warpsim_core)
add_test(NAME v3 COMMAND test_v3)
